apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: blast-quarkus
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/adamevin-tenant/quarkus-blast/blast-quarkus@sha256:253e407ce5653bd632e2cae7368da03274afc53d6772fa203e1f775680ad3490
        name: blast-quarkus
        resources: {}
status: {}
