apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: blast-quarkus
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/adamevin-tenant/quarkus-blast/blast-quarkus@sha256:5283613670be4cb9093435afaafadfe470aaf885791da3baf106dc03326a6b08
        name: blast-quarkus
        resources: {}
status: {}
