apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: blast-quarkus
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/adamevin-tenant/quarkus-blast/blast-quarkus@sha256:0419721de4edc30953daedb13aea07e8de042bc939cce81b24bf70cd0fdb9f5e
        name: blast-quarkus
        resources: {}
status: {}
