apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quarkus-blast
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkus-blast
    app.kubernetes.io/part-of: quarkus-blast
  name: quarkus-blast
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: quarkus-blast
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: quarkus-blast
    spec:
      containers:
      - env:
        - name: QUARKUS_PROFILE
          value: soup
        image: java-quarkus-image:latest
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 5432
        resources:
          requests:
            cpu: 10m
            memory: 512Mi
status: {}
