apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: blast-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: blast-quarkus
    app.kubernetes.io/part-of: quarkus-blast
  name: blast-quarkus
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: quarkus-blast-app
      app.kubernetes.io/instance: blast-quarkus
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: quarkus-blast-app
        app.kubernetes.io/instance: blast-quarkus
    spec:
      containers:
      - env:
        - name: QUARKUS_PROFILE
          value: soup
        image: quay.io/redhat-user-workloads-stage/adamevin-tenant/quarkus-blast/blast-quarkus@sha256:5283613670be4cb9093435afaafadfe470aaf885791da3baf106dc03326a6b08
        name: blast-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 512Mi
status: {}
